<?php
/**
 * CartDetailsResponseData
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UAPAY EscrowBox
 *
 * Escrow box from UAPAY
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the CartDetailsResponseData model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class CartDetailsResponseData 
{
        /**
     * @var int|null
     * @SerializedName("id")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $id;

    /**
     * @var string|null
     * @SerializedName("externalId")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $externalId;

    /**
     * @var string|null
     * @SerializedName("createdAt")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $createdAt;

    /**
     * @var Swagger\Server\Model\DealDetails[]|null
     * @SerializedName("deals")
     * @Assert\All({
     *   @Assert\Type("Swagger\Server\Model\DealDetails")
     * })
     * @Type("array<Swagger\Server\Model\DealDetails>")
     */
    protected $deals;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->id = isset($data['id']) ? $data['id'] : null;
        $this->externalId = isset($data['externalId']) ? $data['externalId'] : null;
        $this->createdAt = isset($data['createdAt']) ? $data['createdAt'] : null;
        $this->deals = isset($data['deals']) ? $data['deals'] : null;
    }

    /**
     * Gets id.
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Sets id.
     *
     * @param int|null $id
     *
     * @return $this
     */
    public function setId($id = null)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets externalId.
     *
     * @return string|null
     */
    public function getExternalId()
    {
        return $this->externalId;
    }

    /**
     * Sets externalId.
     *
     * @param string|null $externalId
     *
     * @return $this
     */
    public function setExternalId($externalId = null)
    {
        $this->externalId = $externalId;

        return $this;
    }

    /**
     * Gets createdAt.
     *
     * @return string|null
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Sets createdAt.
     *
     * @param string|null $createdAt
     *
     * @return $this
     */
    public function setCreatedAt($createdAt = null)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Gets deals.
     *
     * @return Swagger\Server\Model\DealDetails[]|null
     */
    public function getDeals()
    {
        return $this->deals;
    }

    /**
     * Sets deals.
     *
     * @param Swagger\Server\Model\DealDetails[]|null $deals
     *
     * @return $this
     */
    public function setDeals(DealDetails $deals = null)
    {
        $this->deals = $deals;

        return $this;
    }
}


