<?php
/**
 * CreateAdRequestHandlersConfigs
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UAPAY EscrowBox
 *
 * Escrow box from UAPAY
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the CreateAdRequestHandlersConfigs model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class CreateAdRequestHandlersConfigs 
{
        /**
     * @var string|null
     * @SerializedName("type")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $type;

    /**
     * @var string|null
     * @SerializedName("senderFirstName")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $senderFirstName;

    /**
     * @var string|null
     * @SerializedName("senderLastName")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $senderLastName;

    /**
     * @var string|null
     * @SerializedName("senderPatronymic")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $senderPatronymic;

    /**
     * @var string|null
     * @SerializedName("senderPhone")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $senderPhone;

    /**
     * @var string|null
     * @SerializedName("senderEmail")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $senderEmail;

    /**
     * @var string|null
     * @SerializedName("senderCityId")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $senderCityId;

    /**
     * @var string|null
     * @SerializedName("senderOfficeId")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $senderOfficeId;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->type = isset($data['type']) ? $data['type'] : null;
        $this->senderFirstName = isset($data['senderFirstName']) ? $data['senderFirstName'] : null;
        $this->senderLastName = isset($data['senderLastName']) ? $data['senderLastName'] : null;
        $this->senderPatronymic = isset($data['senderPatronymic']) ? $data['senderPatronymic'] : null;
        $this->senderPhone = isset($data['senderPhone']) ? $data['senderPhone'] : null;
        $this->senderEmail = isset($data['senderEmail']) ? $data['senderEmail'] : null;
        $this->senderCityId = isset($data['senderCityId']) ? $data['senderCityId'] : null;
        $this->senderOfficeId = isset($data['senderOfficeId']) ? $data['senderOfficeId'] : null;
    }

    /**
     * Gets type.
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Sets type.
     *
     * @param string|null $type
     *
     * @return $this
     */
    public function setType($type = null)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Gets senderFirstName.
     *
     * @return string|null
     */
    public function getSenderFirstName()
    {
        return $this->senderFirstName;
    }

    /**
     * Sets senderFirstName.
     *
     * @param string|null $senderFirstName
     *
     * @return $this
     */
    public function setSenderFirstName($senderFirstName = null)
    {
        $this->senderFirstName = $senderFirstName;

        return $this;
    }

    /**
     * Gets senderLastName.
     *
     * @return string|null
     */
    public function getSenderLastName()
    {
        return $this->senderLastName;
    }

    /**
     * Sets senderLastName.
     *
     * @param string|null $senderLastName
     *
     * @return $this
     */
    public function setSenderLastName($senderLastName = null)
    {
        $this->senderLastName = $senderLastName;

        return $this;
    }

    /**
     * Gets senderPatronymic.
     *
     * @return string|null
     */
    public function getSenderPatronymic()
    {
        return $this->senderPatronymic;
    }

    /**
     * Sets senderPatronymic.
     *
     * @param string|null $senderPatronymic
     *
     * @return $this
     */
    public function setSenderPatronymic($senderPatronymic = null)
    {
        $this->senderPatronymic = $senderPatronymic;

        return $this;
    }

    /**
     * Gets senderPhone.
     *
     * @return string|null
     */
    public function getSenderPhone()
    {
        return $this->senderPhone;
    }

    /**
     * Sets senderPhone.
     *
     * @param string|null $senderPhone
     *
     * @return $this
     */
    public function setSenderPhone($senderPhone = null)
    {
        $this->senderPhone = $senderPhone;

        return $this;
    }

    /**
     * Gets senderEmail.
     *
     * @return string|null
     */
    public function getSenderEmail()
    {
        return $this->senderEmail;
    }

    /**
     * Sets senderEmail.
     *
     * @param string|null $senderEmail
     *
     * @return $this
     */
    public function setSenderEmail($senderEmail = null)
    {
        $this->senderEmail = $senderEmail;

        return $this;
    }

    /**
     * Gets senderCityId.
     *
     * @return string|null
     */
    public function getSenderCityId()
    {
        return $this->senderCityId;
    }

    /**
     * Sets senderCityId.
     *
     * @param string|null $senderCityId
     *
     * @return $this
     */
    public function setSenderCityId($senderCityId = null)
    {
        $this->senderCityId = $senderCityId;

        return $this;
    }

    /**
     * Gets senderOfficeId.
     *
     * @return string|null
     */
    public function getSenderOfficeId()
    {
        return $this->senderOfficeId;
    }

    /**
     * Sets senderOfficeId.
     *
     * @param string|null $senderOfficeId
     *
     * @return $this
     */
    public function setSenderOfficeId($senderOfficeId = null)
    {
        $this->senderOfficeId = $senderOfficeId;

        return $this;
    }
}


