<?php
/**
 * CreateDealRequestPayment
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UAPAY EscrowBox
 *
 * Escrow box from UAPAY
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the CreateDealRequestPayment model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class CreateDealRequestPayment 
{
        /**
     * @var string|null
     * @SerializedName("type")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $type;

    /**
     * @var string|null
     * @SerializedName("cardToId")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $cardToId;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->type = isset($data['type']) ? $data['type'] : null;
        $this->cardToId = isset($data['cardToId']) ? $data['cardToId'] : null;
    }

    /**
     * Gets type.
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Sets type.
     *
     * @param string|null $type
     *
     * @return $this
     */
    public function setType($type = null)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Gets cardToId.
     *
     * @return string|null
     */
    public function getCardToId()
    {
        return $this->cardToId;
    }

    /**
     * Sets cardToId.
     *
     * @param string|null $cardToId
     *
     * @return $this
     */
    public function setCardToId($cardToId = null)
    {
        $this->cardToId = $cardToId;

        return $this;
    }
}


