<?php
/**
 * DealDetails
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UAPAY EscrowBox
 *
 * Escrow box from UAPAY
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the DealDetails model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class DealDetails 
{
        /**
     * @var int|null
     * @SerializedName("id")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $id;

    /**
     * @var string|null
     * @SerializedName("externalId")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $externalId;

    /**
     * @var int|null
     * @SerializedName("cartId")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $cartId;

    /**
     * @var string|null
     * @SerializedName("productTitle")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $productTitle;

    /**
     * @var int|null
     * @SerializedName("productWeight")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $productWeight;

    /**
     * @var int|null
     * @SerializedName("productPrice")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $productPrice;

    /**
     * @var int|null
     * @SerializedName("handlerPrice")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $handlerPrice;

    /**
     * @var string|null
     * @SerializedName("status")
     * @Assert\Choice({ "NEW", "PAID", "CONFIRMED", "SENT", "DELIVERED", "FINISHED", "REJECTED", "EXPIRED" })
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $status;

    /**
     * @var string|null
     * @SerializedName("reasonStep")
     * @Assert\Choice({ "NEW", "PAID", "CONFIRMED", "SENT", "DELIVERED" })
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $reasonStep;

    /**
     * @var string|null
     * @SerializedName("sellerFirstName")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $sellerFirstName;

    /**
     * @var string|null
     * @SerializedName("sellerLastName")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $sellerLastName;

    /**
     * @var string|null
     * @SerializedName("sellerPatronymic")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $sellerPatronymic;

    /**
     * @var string|null
     * @SerializedName("sellerPhone")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $sellerPhone;

    /**
     * @var string|null
     * @SerializedName("sellerEmail")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $sellerEmail;

    /**
     * @var string|null
     * @SerializedName("buyerFirstName")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $buyerFirstName;

    /**
     * @var string|null
     * @SerializedName("buyerLastName")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $buyerLastName;

    /**
     * @var string|null
     * @SerializedName("buyerPatronymic")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $buyerPatronymic;

    /**
     * @var string|null
     * @SerializedName("buyerPhone")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $buyerPhone;

    /**
     * @var string|null
     * @SerializedName("buyerEmail")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $buyerEmail;

    /**
     * @var string|null
     * @SerializedName("adId")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $adId;

    /**
     * @var string|null
     * @SerializedName("lg")
     * @Assert\Choice({ "uk", "ru", "en" })
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $lg;

    /**
     * @var string|null
     * @SerializedName("createdAt")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $createdAt;

    /**
     * @var Swagger\Server\Model\DealDetailsHandler|null
     * @SerializedName("handler")
     * @Assert\Type("Swagger\Server\Model\DealDetailsHandler")
     * @Type("Swagger\Server\Model\DealDetailsHandler")
     */
    protected $handler;

    /**
     * @var Swagger\Server\Model\DealDetailsHandlerPayment|null
     * @SerializedName("handlerPayment")
     * @Assert\Type("Swagger\Server\Model\DealDetailsHandlerPayment")
     * @Type("Swagger\Server\Model\DealDetailsHandlerPayment")
     */
    protected $handlerPayment;

    /**
     * @var Swagger\Server\Model\DealDetailsProductPayment|null
     * @SerializedName("productPayment")
     * @Assert\Type("Swagger\Server\Model\DealDetailsProductPayment")
     * @Type("Swagger\Server\Model\DealDetailsProductPayment")
     */
    protected $productPayment;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->id = isset($data['id']) ? $data['id'] : null;
        $this->externalId = isset($data['externalId']) ? $data['externalId'] : null;
        $this->cartId = isset($data['cartId']) ? $data['cartId'] : null;
        $this->productTitle = isset($data['productTitle']) ? $data['productTitle'] : null;
        $this->productWeight = isset($data['productWeight']) ? $data['productWeight'] : null;
        $this->productPrice = isset($data['productPrice']) ? $data['productPrice'] : null;
        $this->handlerPrice = isset($data['handlerPrice']) ? $data['handlerPrice'] : null;
        $this->status = isset($data['status']) ? $data['status'] : null;
        $this->reasonStep = isset($data['reasonStep']) ? $data['reasonStep'] : null;
        $this->sellerFirstName = isset($data['sellerFirstName']) ? $data['sellerFirstName'] : null;
        $this->sellerLastName = isset($data['sellerLastName']) ? $data['sellerLastName'] : null;
        $this->sellerPatronymic = isset($data['sellerPatronymic']) ? $data['sellerPatronymic'] : null;
        $this->sellerPhone = isset($data['sellerPhone']) ? $data['sellerPhone'] : null;
        $this->sellerEmail = isset($data['sellerEmail']) ? $data['sellerEmail'] : null;
        $this->buyerFirstName = isset($data['buyerFirstName']) ? $data['buyerFirstName'] : null;
        $this->buyerLastName = isset($data['buyerLastName']) ? $data['buyerLastName'] : null;
        $this->buyerPatronymic = isset($data['buyerPatronymic']) ? $data['buyerPatronymic'] : null;
        $this->buyerPhone = isset($data['buyerPhone']) ? $data['buyerPhone'] : null;
        $this->buyerEmail = isset($data['buyerEmail']) ? $data['buyerEmail'] : null;
        $this->adId = isset($data['adId']) ? $data['adId'] : null;
        $this->lg = isset($data['lg']) ? $data['lg'] : null;
        $this->createdAt = isset($data['createdAt']) ? $data['createdAt'] : null;
        $this->handler = isset($data['handler']) ? $data['handler'] : null;
        $this->handlerPayment = isset($data['handlerPayment']) ? $data['handlerPayment'] : null;
        $this->productPayment = isset($data['productPayment']) ? $data['productPayment'] : null;
    }

    /**
     * Gets id.
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Sets id.
     *
     * @param int|null $id
     *
     * @return $this
     */
    public function setId($id = null)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets externalId.
     *
     * @return string|null
     */
    public function getExternalId()
    {
        return $this->externalId;
    }

    /**
     * Sets externalId.
     *
     * @param string|null $externalId
     *
     * @return $this
     */
    public function setExternalId($externalId = null)
    {
        $this->externalId = $externalId;

        return $this;
    }

    /**
     * Gets cartId.
     *
     * @return int|null
     */
    public function getCartId()
    {
        return $this->cartId;
    }

    /**
     * Sets cartId.
     *
     * @param int|null $cartId
     *
     * @return $this
     */
    public function setCartId($cartId = null)
    {
        $this->cartId = $cartId;

        return $this;
    }

    /**
     * Gets productTitle.
     *
     * @return string|null
     */
    public function getProductTitle()
    {
        return $this->productTitle;
    }

    /**
     * Sets productTitle.
     *
     * @param string|null $productTitle
     *
     * @return $this
     */
    public function setProductTitle($productTitle = null)
    {
        $this->productTitle = $productTitle;

        return $this;
    }

    /**
     * Gets productWeight.
     *
     * @return int|null
     */
    public function getProductWeight()
    {
        return $this->productWeight;
    }

    /**
     * Sets productWeight.
     *
     * @param int|null $productWeight
     *
     * @return $this
     */
    public function setProductWeight($productWeight = null)
    {
        $this->productWeight = $productWeight;

        return $this;
    }

    /**
     * Gets productPrice.
     *
     * @return int|null
     */
    public function getProductPrice()
    {
        return $this->productPrice;
    }

    /**
     * Sets productPrice.
     *
     * @param int|null $productPrice
     *
     * @return $this
     */
    public function setProductPrice($productPrice = null)
    {
        $this->productPrice = $productPrice;

        return $this;
    }

    /**
     * Gets handlerPrice.
     *
     * @return int|null
     */
    public function getHandlerPrice()
    {
        return $this->handlerPrice;
    }

    /**
     * Sets handlerPrice.
     *
     * @param int|null $handlerPrice
     *
     * @return $this
     */
    public function setHandlerPrice($handlerPrice = null)
    {
        $this->handlerPrice = $handlerPrice;

        return $this;
    }

    /**
     * Gets status.
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Sets status.
     *
     * @param string|null $status
     *
     * @return $this
     */
    public function setStatus($status = null)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Gets reasonStep.
     *
     * @return string|null
     */
    public function getReasonStep()
    {
        return $this->reasonStep;
    }

    /**
     * Sets reasonStep.
     *
     * @param string|null $reasonStep
     *
     * @return $this
     */
    public function setReasonStep($reasonStep = null)
    {
        $this->reasonStep = $reasonStep;

        return $this;
    }

    /**
     * Gets sellerFirstName.
     *
     * @return string|null
     */
    public function getSellerFirstName()
    {
        return $this->sellerFirstName;
    }

    /**
     * Sets sellerFirstName.
     *
     * @param string|null $sellerFirstName
     *
     * @return $this
     */
    public function setSellerFirstName($sellerFirstName = null)
    {
        $this->sellerFirstName = $sellerFirstName;

        return $this;
    }

    /**
     * Gets sellerLastName.
     *
     * @return string|null
     */
    public function getSellerLastName()
    {
        return $this->sellerLastName;
    }

    /**
     * Sets sellerLastName.
     *
     * @param string|null $sellerLastName
     *
     * @return $this
     */
    public function setSellerLastName($sellerLastName = null)
    {
        $this->sellerLastName = $sellerLastName;

        return $this;
    }

    /**
     * Gets sellerPatronymic.
     *
     * @return string|null
     */
    public function getSellerPatronymic()
    {
        return $this->sellerPatronymic;
    }

    /**
     * Sets sellerPatronymic.
     *
     * @param string|null $sellerPatronymic
     *
     * @return $this
     */
    public function setSellerPatronymic($sellerPatronymic = null)
    {
        $this->sellerPatronymic = $sellerPatronymic;

        return $this;
    }

    /**
     * Gets sellerPhone.
     *
     * @return string|null
     */
    public function getSellerPhone()
    {
        return $this->sellerPhone;
    }

    /**
     * Sets sellerPhone.
     *
     * @param string|null $sellerPhone
     *
     * @return $this
     */
    public function setSellerPhone($sellerPhone = null)
    {
        $this->sellerPhone = $sellerPhone;

        return $this;
    }

    /**
     * Gets sellerEmail.
     *
     * @return string|null
     */
    public function getSellerEmail()
    {
        return $this->sellerEmail;
    }

    /**
     * Sets sellerEmail.
     *
     * @param string|null $sellerEmail
     *
     * @return $this
     */
    public function setSellerEmail($sellerEmail = null)
    {
        $this->sellerEmail = $sellerEmail;

        return $this;
    }

    /**
     * Gets buyerFirstName.
     *
     * @return string|null
     */
    public function getBuyerFirstName()
    {
        return $this->buyerFirstName;
    }

    /**
     * Sets buyerFirstName.
     *
     * @param string|null $buyerFirstName
     *
     * @return $this
     */
    public function setBuyerFirstName($buyerFirstName = null)
    {
        $this->buyerFirstName = $buyerFirstName;

        return $this;
    }

    /**
     * Gets buyerLastName.
     *
     * @return string|null
     */
    public function getBuyerLastName()
    {
        return $this->buyerLastName;
    }

    /**
     * Sets buyerLastName.
     *
     * @param string|null $buyerLastName
     *
     * @return $this
     */
    public function setBuyerLastName($buyerLastName = null)
    {
        $this->buyerLastName = $buyerLastName;

        return $this;
    }

    /**
     * Gets buyerPatronymic.
     *
     * @return string|null
     */
    public function getBuyerPatronymic()
    {
        return $this->buyerPatronymic;
    }

    /**
     * Sets buyerPatronymic.
     *
     * @param string|null $buyerPatronymic
     *
     * @return $this
     */
    public function setBuyerPatronymic($buyerPatronymic = null)
    {
        $this->buyerPatronymic = $buyerPatronymic;

        return $this;
    }

    /**
     * Gets buyerPhone.
     *
     * @return string|null
     */
    public function getBuyerPhone()
    {
        return $this->buyerPhone;
    }

    /**
     * Sets buyerPhone.
     *
     * @param string|null $buyerPhone
     *
     * @return $this
     */
    public function setBuyerPhone($buyerPhone = null)
    {
        $this->buyerPhone = $buyerPhone;

        return $this;
    }

    /**
     * Gets buyerEmail.
     *
     * @return string|null
     */
    public function getBuyerEmail()
    {
        return $this->buyerEmail;
    }

    /**
     * Sets buyerEmail.
     *
     * @param string|null $buyerEmail
     *
     * @return $this
     */
    public function setBuyerEmail($buyerEmail = null)
    {
        $this->buyerEmail = $buyerEmail;

        return $this;
    }

    /**
     * Gets adId.
     *
     * @return string|null
     */
    public function getAdId()
    {
        return $this->adId;
    }

    /**
     * Sets adId.
     *
     * @param string|null $adId
     *
     * @return $this
     */
    public function setAdId($adId = null)
    {
        $this->adId = $adId;

        return $this;
    }

    /**
     * Gets lg.
     *
     * @return string|null
     */
    public function getLg()
    {
        return $this->lg;
    }

    /**
     * Sets lg.
     *
     * @param string|null $lg
     *
     * @return $this
     */
    public function setLg($lg = null)
    {
        $this->lg = $lg;

        return $this;
    }

    /**
     * Gets createdAt.
     *
     * @return string|null
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Sets createdAt.
     *
     * @param string|null $createdAt
     *
     * @return $this
     */
    public function setCreatedAt($createdAt = null)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Gets handler.
     *
     * @return Swagger\Server\Model\DealDetailsHandler|null
     */
    public function getHandler()
    {
        return $this->handler;
    }

    /**
     * Sets handler.
     *
     * @param Swagger\Server\Model\DealDetailsHandler|null $handler
     *
     * @return $this
     */
    public function setHandler(DealDetailsHandler $handler = null)
    {
        $this->handler = $handler;

        return $this;
    }

    /**
     * Gets handlerPayment.
     *
     * @return Swagger\Server\Model\DealDetailsHandlerPayment|null
     */
    public function getHandlerPayment()
    {
        return $this->handlerPayment;
    }

    /**
     * Sets handlerPayment.
     *
     * @param Swagger\Server\Model\DealDetailsHandlerPayment|null $handlerPayment
     *
     * @return $this
     */
    public function setHandlerPayment(DealDetailsHandlerPayment $handlerPayment = null)
    {
        $this->handlerPayment = $handlerPayment;

        return $this;
    }

    /**
     * Gets productPayment.
     *
     * @return Swagger\Server\Model\DealDetailsProductPayment|null
     */
    public function getProductPayment()
    {
        return $this->productPayment;
    }

    /**
     * Sets productPayment.
     *
     * @param Swagger\Server\Model\DealDetailsProductPayment|null $productPayment
     *
     * @return $this
     */
    public function setProductPayment(DealDetailsProductPayment $productPayment = null)
    {
        $this->productPayment = $productPayment;

        return $this;
    }
}


