<?php
/**
 * DealDetailsHandler
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UAPAY EscrowBox
 *
 * Escrow box from UAPAY
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the DealDetailsHandler model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class DealDetailsHandler 
{
        /**
     * @var string|null
     * @SerializedName("type")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $type;

    /**
     * @var string|null
     * @SerializedName("status")
     * @Assert\Choice({ "NEW", "CREATED", "SENT", "DELIVERED", "FINISHED", "CANCELED", "REJECTED", "EXPIRED" })
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $status;

    /**
     * @var string|null
     * @SerializedName("statusCode")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $statusCode;

    /**
     * @var string|null
     * @SerializedName("statusText")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $statusText;

    /**
     * @var int|null
     * @SerializedName("waybillNumber")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $waybillNumber;

    /**
     * @var string|null
     * @SerializedName("senderCityId")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $senderCityId;

    /**
     * @var string|null
     * @SerializedName("senderCityName")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $senderCityName;

    /**
     * @var string|null
     * @SerializedName("senderOfficeId")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $senderOfficeId;

    /**
     * @var string|null
     * @SerializedName("senderOfficeName")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $senderOfficeName;

    /**
     * @var string|null
     * @SerializedName("recipientCityId")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $recipientCityId;

    /**
     * @var string|null
     * @SerializedName("recipientCityName")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $recipientCityName;

    /**
     * @var string|null
     * @SerializedName("recipientOfficeId")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $recipientOfficeId;

    /**
     * @var string|null
     * @SerializedName("recipientOfficeName")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $recipientOfficeName;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->type = isset($data['type']) ? $data['type'] : null;
        $this->status = isset($data['status']) ? $data['status'] : null;
        $this->statusCode = isset($data['statusCode']) ? $data['statusCode'] : null;
        $this->statusText = isset($data['statusText']) ? $data['statusText'] : null;
        $this->waybillNumber = isset($data['waybillNumber']) ? $data['waybillNumber'] : null;
        $this->senderCityId = isset($data['senderCityId']) ? $data['senderCityId'] : null;
        $this->senderCityName = isset($data['senderCityName']) ? $data['senderCityName'] : null;
        $this->senderOfficeId = isset($data['senderOfficeId']) ? $data['senderOfficeId'] : null;
        $this->senderOfficeName = isset($data['senderOfficeName']) ? $data['senderOfficeName'] : null;
        $this->recipientCityId = isset($data['recipientCityId']) ? $data['recipientCityId'] : null;
        $this->recipientCityName = isset($data['recipientCityName']) ? $data['recipientCityName'] : null;
        $this->recipientOfficeId = isset($data['recipientOfficeId']) ? $data['recipientOfficeId'] : null;
        $this->recipientOfficeName = isset($data['recipientOfficeName']) ? $data['recipientOfficeName'] : null;
    }

    /**
     * Gets type.
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Sets type.
     *
     * @param string|null $type
     *
     * @return $this
     */
    public function setType($type = null)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Gets status.
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Sets status.
     *
     * @param string|null $status
     *
     * @return $this
     */
    public function setStatus($status = null)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Gets statusCode.
     *
     * @return string|null
     */
    public function getStatusCode()
    {
        return $this->statusCode;
    }

    /**
     * Sets statusCode.
     *
     * @param string|null $statusCode
     *
     * @return $this
     */
    public function setStatusCode($statusCode = null)
    {
        $this->statusCode = $statusCode;

        return $this;
    }

    /**
     * Gets statusText.
     *
     * @return string|null
     */
    public function getStatusText()
    {
        return $this->statusText;
    }

    /**
     * Sets statusText.
     *
     * @param string|null $statusText
     *
     * @return $this
     */
    public function setStatusText($statusText = null)
    {
        $this->statusText = $statusText;

        return $this;
    }

    /**
     * Gets waybillNumber.
     *
     * @return int|null
     */
    public function getWaybillNumber()
    {
        return $this->waybillNumber;
    }

    /**
     * Sets waybillNumber.
     *
     * @param int|null $waybillNumber
     *
     * @return $this
     */
    public function setWaybillNumber($waybillNumber = null)
    {
        $this->waybillNumber = $waybillNumber;

        return $this;
    }

    /**
     * Gets senderCityId.
     *
     * @return string|null
     */
    public function getSenderCityId()
    {
        return $this->senderCityId;
    }

    /**
     * Sets senderCityId.
     *
     * @param string|null $senderCityId
     *
     * @return $this
     */
    public function setSenderCityId($senderCityId = null)
    {
        $this->senderCityId = $senderCityId;

        return $this;
    }

    /**
     * Gets senderCityName.
     *
     * @return string|null
     */
    public function getSenderCityName()
    {
        return $this->senderCityName;
    }

    /**
     * Sets senderCityName.
     *
     * @param string|null $senderCityName
     *
     * @return $this
     */
    public function setSenderCityName($senderCityName = null)
    {
        $this->senderCityName = $senderCityName;

        return $this;
    }

    /**
     * Gets senderOfficeId.
     *
     * @return string|null
     */
    public function getSenderOfficeId()
    {
        return $this->senderOfficeId;
    }

    /**
     * Sets senderOfficeId.
     *
     * @param string|null $senderOfficeId
     *
     * @return $this
     */
    public function setSenderOfficeId($senderOfficeId = null)
    {
        $this->senderOfficeId = $senderOfficeId;

        return $this;
    }

    /**
     * Gets senderOfficeName.
     *
     * @return string|null
     */
    public function getSenderOfficeName()
    {
        return $this->senderOfficeName;
    }

    /**
     * Sets senderOfficeName.
     *
     * @param string|null $senderOfficeName
     *
     * @return $this
     */
    public function setSenderOfficeName($senderOfficeName = null)
    {
        $this->senderOfficeName = $senderOfficeName;

        return $this;
    }

    /**
     * Gets recipientCityId.
     *
     * @return string|null
     */
    public function getRecipientCityId()
    {
        return $this->recipientCityId;
    }

    /**
     * Sets recipientCityId.
     *
     * @param string|null $recipientCityId
     *
     * @return $this
     */
    public function setRecipientCityId($recipientCityId = null)
    {
        $this->recipientCityId = $recipientCityId;

        return $this;
    }

    /**
     * Gets recipientCityName.
     *
     * @return string|null
     */
    public function getRecipientCityName()
    {
        return $this->recipientCityName;
    }

    /**
     * Sets recipientCityName.
     *
     * @param string|null $recipientCityName
     *
     * @return $this
     */
    public function setRecipientCityName($recipientCityName = null)
    {
        $this->recipientCityName = $recipientCityName;

        return $this;
    }

    /**
     * Gets recipientOfficeId.
     *
     * @return string|null
     */
    public function getRecipientOfficeId()
    {
        return $this->recipientOfficeId;
    }

    /**
     * Sets recipientOfficeId.
     *
     * @param string|null $recipientOfficeId
     *
     * @return $this
     */
    public function setRecipientOfficeId($recipientOfficeId = null)
    {
        $this->recipientOfficeId = $recipientOfficeId;

        return $this;
    }

    /**
     * Gets recipientOfficeName.
     *
     * @return string|null
     */
    public function getRecipientOfficeName()
    {
        return $this->recipientOfficeName;
    }

    /**
     * Sets recipientOfficeName.
     *
     * @param string|null $recipientOfficeName
     *
     * @return $this
     */
    public function setRecipientOfficeName($recipientOfficeName = null)
    {
        $this->recipientOfficeName = $recipientOfficeName;

        return $this;
    }
}


