<?php
/**
 * HandlerCostResponseData
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UAPAY EscrowBox
 *
 * Escrow box from UAPAY
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the HandlerCostResponseData model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class HandlerCostResponseData 
{
        /**
     * @var int|null
     * @SerializedName("handlerPrice")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $handlerPrice;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->handlerPrice = isset($data['handlerPrice']) ? $data['handlerPrice'] : null;
    }

    /**
     * Gets handlerPrice.
     *
     * @return int|null
     */
    public function getHandlerPrice()
    {
        return $this->handlerPrice;
    }

    /**
     * Sets handlerPrice.
     *
     * @param int|null $handlerPrice
     *
     * @return $this
     */
    public function setHandlerPrice($handlerPrice = null)
    {
        $this->handlerPrice = $handlerPrice;

        return $this;
    }
}


