<?php
/**
 * PayerCommissionResponseData
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UAPAY EscrowBox
 *
 * Escrow box from UAPAY
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the PayerCommissionResponseData model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class PayerCommissionResponseData 
{
        /**
     * @var int|null
     * @SerializedName("fixed")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $fixed;

    /**
     * @var float|null
     * @SerializedName("percents")
     * @Assert\Type("float")
     * @Type("float")
     */
    protected $percents;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->fixed = isset($data['fixed']) ? $data['fixed'] : null;
        $this->percents = isset($data['percents']) ? $data['percents'] : null;
    }

    /**
     * Gets fixed.
     *
     * @return int|null
     */
    public function getFixed()
    {
        return $this->fixed;
    }

    /**
     * Sets fixed.
     *
     * @param int|null $fixed
     *
     * @return $this
     */
    public function setFixed($fixed = null)
    {
        $this->fixed = $fixed;

        return $this;
    }

    /**
     * Gets percents.
     *
     * @return float|null
     */
    public function getPercents()
    {
        return $this->percents;
    }

    /**
     * Sets percents.
     *
     * @param float|null $percents
     *
     * @return $this
     */
    public function setPercents($percents = null)
    {
        $this->percents = $percents;

        return $this;
    }
}


