<?php
/**
 * PayerCommissionAmountResponseData
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UAPAY EscrowBox
 *
 * Escrow box from UAPAY
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the PayerCommissionAmountResponseData model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class PayerCommissionAmountResponseData 
{
        /**
     * @var int|null
     * @SerializedName("commissionAmount")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $commissionAmount;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->commissionAmount = isset($data['commissionAmount']) ? $data['commissionAmount'] : null;
    }

    /**
     * Gets commissionAmount.
     *
     * @return int|null
     */
    public function getCommissionAmount()
    {
        return $this->commissionAmount;
    }

    /**
     * Sets commissionAmount.
     *
     * @param int|null $commissionAmount
     *
     * @return $this
     */
    public function setCommissionAmount($commissionAmount = null)
    {
        $this->commissionAmount = $commissionAmount;

        return $this;
    }
}


