<?php
/**
 * PaymentRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UAPAY EscrowBox
 *
 * Escrow box from UAPAY
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the PaymentRequest model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class PaymentRequest 
{
        /**
     * @var string
     * @SerializedName("remoteIP")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $remoteIP;

    /**
     * @var Swagger\Server\Model\PaymentRequestCard
     * @SerializedName("card")
     * @Assert\NotNull()
     * @Assert\Type("Swagger\Server\Model\PaymentRequestCard")
     * @Type("Swagger\Server\Model\PaymentRequestCard")
     */
    protected $card;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->remoteIP = isset($data['remoteIP']) ? $data['remoteIP'] : null;
        $this->card = isset($data['card']) ? $data['card'] : null;
    }

    /**
     * Gets remoteIP.
     *
     * @return string
     */
    public function getRemoteIP()
    {
        return $this->remoteIP;
    }

    /**
     * Sets remoteIP.
     *
     * @param string $remoteIP
     *
     * @return $this
     */
    public function setRemoteIP($remoteIP)
    {
        $this->remoteIP = $remoteIP;

        return $this;
    }

    /**
     * Gets card.
     *
     * @return Swagger\Server\Model\PaymentRequestCard
     */
    public function getCard()
    {
        return $this->card;
    }

    /**
     * Sets card.
     *
     * @param Swagger\Server\Model\PaymentRequestCard $card
     *
     * @return $this
     */
    public function setCard(PaymentRequestCard $card)
    {
        $this->card = $card;

        return $this;
    }
}


