<?php
/**
 * HelpersApiInterfaceTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Tests\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UAPAY EscrowBox
 *
 * Escrow box from UAPAY
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Server\Tests\Api;

use Swagger\Server\Configuration;
use Swagger\Server\ApiClient;
use Swagger\Server\ApiException;
use Swagger\Server\ObjectSerializer;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

/**
 * HelpersApiInterfaceTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Server\Tests\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class HelpersApiInterfaceTest extends WebTestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for handlersHandlerTypeCitiesCityIdOfficesGet
     *
     * List offices from handler by cityId.
     *
     */
    public function testHandlersHandlerTypeCitiesCityIdOfficesGet()
    {
        $client = static::createClient();

        $path = '/handlers/{handlerType}/cities/{cityId}/offices';
        $pattern = '{handlerType}';
        $data = $this->genTestData('[a-z0-9]+');
        $path = str_replace($pattern, $data, $path);
        $pattern = '{cityId}';
        $data = $this->genTestData('[a-z0-9]+');
        $path = str_replace($pattern, $data, $path);

        $crawler = $client->request('GET', $path);
    }

    /**
     * Test case for handlersHandlerTypeCitiesGet
     *
     * List cities from handler.
     *
     */
    public function testHandlersHandlerTypeCitiesGet()
    {
        $client = static::createClient();

        $path = '/handlers/{handlerType}/cities';
        $pattern = '{handlerType}';
        $data = $this->genTestData('[a-z0-9]+');
        $path = str_replace($pattern, $data, $path);

        $crawler = $client->request('GET', $path);
    }

    /**
     * Test case for handlersHandlerTypeCostsGet
     *
     * Calculate delivery cost.
     *
     */
    public function testHandlersHandlerTypeCostsGet()
    {
        $client = static::createClient();

        $path = '/handlers/{handlerType}/costs';
        $pattern = '{handlerType}';
        $data = $this->genTestData('[a-z0-9]+');
        $path = str_replace($pattern, $data, $path);

        $crawler = $client->request('GET', $path);
    }

    /**
     * Test case for payersPayerTypeCommissionAmountGet
     *
     * Calculate commission amount from income amount for payer.
     *
     */
    public function testPayersPayerTypeCommissionAmountGet()
    {
        $client = static::createClient();

        $path = '/payers/{payerType}/commissionAmount';
        $pattern = '{payerType}';
        $data = $this->genTestData('[a-z0-9]+');
        $path = str_replace($pattern, $data, $path);

        $crawler = $client->request('GET', $path);
    }

    /**
     * Test case for payersPayerTypeGet
     *
     * Get commission object of payer.
     *
     */
    public function testPayersPayerTypeGet()
    {
        $client = static::createClient();

        $path = '/payers/{payerType}';
        $pattern = '{payerType}';
        $data = $this->genTestData('[a-z0-9]+');
        $path = str_replace($pattern, $data, $path);

        $crawler = $client->request('GET', $path);
    }

    protected function genTestData($regexp)
    {
        $grammar  = new \Hoa\File\Read('hoa://Library/Regex/Grammar.pp');
        $compiler = \Hoa\Compiler\Llk\Llk::load($grammar);
        $ast      = $compiler->parse($regexp);
        $generator = new \Hoa\Regex\Visitor\Isotropic(new \Hoa\Math\Sampler\Random());

        return $generator->visit($ast); 
    }
}
