<?php
/**
 * CreateDealRequestHandler
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UAPAY EscrowBox
 *
 * Escrow box from UAPAY
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * CreateDealRequestHandler Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CreateDealRequestHandler implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'CreateDealRequest_handler';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'type' => 'string',
        'sender_first_name' => 'string',
        'sender_last_name' => 'string',
        'sender_patronymic' => 'string',
        'sender_phone' => 'string',
        'sender_email' => 'string',
        'sender_city_id' => 'string',
        'sender_office_id' => 'string',
        'recipient_first_name' => 'string',
        'recipient_last_name' => 'string',
        'recipient_patronymic' => 'string',
        'recipient_phone' => 'string',
        'recipient_email' => 'string',
        'recipient_city_id' => 'string',
        'recipient_office_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'type' => null,
        'sender_first_name' => null,
        'sender_last_name' => null,
        'sender_patronymic' => null,
        'sender_phone' => null,
        'sender_email' => null,
        'sender_city_id' => null,
        'sender_office_id' => null,
        'recipient_first_name' => null,
        'recipient_last_name' => null,
        'recipient_patronymic' => null,
        'recipient_phone' => null,
        'recipient_email' => null,
        'recipient_city_id' => null,
        'recipient_office_id' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'type' => 'type',
        'sender_first_name' => 'senderFirstName',
        'sender_last_name' => 'senderLastName',
        'sender_patronymic' => 'senderPatronymic',
        'sender_phone' => 'senderPhone',
        'sender_email' => 'senderEmail',
        'sender_city_id' => 'senderCityId',
        'sender_office_id' => 'senderOfficeId',
        'recipient_first_name' => 'recipientFirstName',
        'recipient_last_name' => 'recipientLastName',
        'recipient_patronymic' => 'recipientPatronymic',
        'recipient_phone' => 'recipientPhone',
        'recipient_email' => 'recipientEmail',
        'recipient_city_id' => 'recipientCityId',
        'recipient_office_id' => 'recipientOfficeId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'type' => 'setType',
        'sender_first_name' => 'setSenderFirstName',
        'sender_last_name' => 'setSenderLastName',
        'sender_patronymic' => 'setSenderPatronymic',
        'sender_phone' => 'setSenderPhone',
        'sender_email' => 'setSenderEmail',
        'sender_city_id' => 'setSenderCityId',
        'sender_office_id' => 'setSenderOfficeId',
        'recipient_first_name' => 'setRecipientFirstName',
        'recipient_last_name' => 'setRecipientLastName',
        'recipient_patronymic' => 'setRecipientPatronymic',
        'recipient_phone' => 'setRecipientPhone',
        'recipient_email' => 'setRecipientEmail',
        'recipient_city_id' => 'setRecipientCityId',
        'recipient_office_id' => 'setRecipientOfficeId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'type' => 'getType',
        'sender_first_name' => 'getSenderFirstName',
        'sender_last_name' => 'getSenderLastName',
        'sender_patronymic' => 'getSenderPatronymic',
        'sender_phone' => 'getSenderPhone',
        'sender_email' => 'getSenderEmail',
        'sender_city_id' => 'getSenderCityId',
        'sender_office_id' => 'getSenderOfficeId',
        'recipient_first_name' => 'getRecipientFirstName',
        'recipient_last_name' => 'getRecipientLastName',
        'recipient_patronymic' => 'getRecipientPatronymic',
        'recipient_phone' => 'getRecipientPhone',
        'recipient_email' => 'getRecipientEmail',
        'recipient_city_id' => 'getRecipientCityId',
        'recipient_office_id' => 'getRecipientOfficeId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['sender_first_name'] = isset($data['sender_first_name']) ? $data['sender_first_name'] : null;
        $this->container['sender_last_name'] = isset($data['sender_last_name']) ? $data['sender_last_name'] : null;
        $this->container['sender_patronymic'] = isset($data['sender_patronymic']) ? $data['sender_patronymic'] : null;
        $this->container['sender_phone'] = isset($data['sender_phone']) ? $data['sender_phone'] : null;
        $this->container['sender_email'] = isset($data['sender_email']) ? $data['sender_email'] : null;
        $this->container['sender_city_id'] = isset($data['sender_city_id']) ? $data['sender_city_id'] : null;
        $this->container['sender_office_id'] = isset($data['sender_office_id']) ? $data['sender_office_id'] : null;
        $this->container['recipient_first_name'] = isset($data['recipient_first_name']) ? $data['recipient_first_name'] : null;
        $this->container['recipient_last_name'] = isset($data['recipient_last_name']) ? $data['recipient_last_name'] : null;
        $this->container['recipient_patronymic'] = isset($data['recipient_patronymic']) ? $data['recipient_patronymic'] : null;
        $this->container['recipient_phone'] = isset($data['recipient_phone']) ? $data['recipient_phone'] : null;
        $this->container['recipient_email'] = isset($data['recipient_email']) ? $data['recipient_email'] : null;
        $this->container['recipient_city_id'] = isset($data['recipient_city_id']) ? $data['recipient_city_id'] : null;
        $this->container['recipient_office_id'] = isset($data['recipient_office_id']) ? $data['recipient_office_id'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return $this
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets sender_first_name
     *
     * @return string
     */
    public function getSenderFirstName()
    {
        return $this->container['sender_first_name'];
    }

    /**
     * Sets sender_first_name
     *
     * @param string $sender_first_name sender_first_name
     *
     * @return $this
     */
    public function setSenderFirstName($sender_first_name)
    {
        $this->container['sender_first_name'] = $sender_first_name;

        return $this;
    }

    /**
     * Gets sender_last_name
     *
     * @return string
     */
    public function getSenderLastName()
    {
        return $this->container['sender_last_name'];
    }

    /**
     * Sets sender_last_name
     *
     * @param string $sender_last_name sender_last_name
     *
     * @return $this
     */
    public function setSenderLastName($sender_last_name)
    {
        $this->container['sender_last_name'] = $sender_last_name;

        return $this;
    }

    /**
     * Gets sender_patronymic
     *
     * @return string
     */
    public function getSenderPatronymic()
    {
        return $this->container['sender_patronymic'];
    }

    /**
     * Sets sender_patronymic
     *
     * @param string $sender_patronymic sender_patronymic
     *
     * @return $this
     */
    public function setSenderPatronymic($sender_patronymic)
    {
        $this->container['sender_patronymic'] = $sender_patronymic;

        return $this;
    }

    /**
     * Gets sender_phone
     *
     * @return string
     */
    public function getSenderPhone()
    {
        return $this->container['sender_phone'];
    }

    /**
     * Sets sender_phone
     *
     * @param string $sender_phone sender_phone
     *
     * @return $this
     */
    public function setSenderPhone($sender_phone)
    {
        $this->container['sender_phone'] = $sender_phone;

        return $this;
    }

    /**
     * Gets sender_email
     *
     * @return string
     */
    public function getSenderEmail()
    {
        return $this->container['sender_email'];
    }

    /**
     * Sets sender_email
     *
     * @param string $sender_email sender_email
     *
     * @return $this
     */
    public function setSenderEmail($sender_email)
    {
        $this->container['sender_email'] = $sender_email;

        return $this;
    }

    /**
     * Gets sender_city_id
     *
     * @return string
     */
    public function getSenderCityId()
    {
        return $this->container['sender_city_id'];
    }

    /**
     * Sets sender_city_id
     *
     * @param string $sender_city_id sender_city_id
     *
     * @return $this
     */
    public function setSenderCityId($sender_city_id)
    {
        $this->container['sender_city_id'] = $sender_city_id;

        return $this;
    }

    /**
     * Gets sender_office_id
     *
     * @return string
     */
    public function getSenderOfficeId()
    {
        return $this->container['sender_office_id'];
    }

    /**
     * Sets sender_office_id
     *
     * @param string $sender_office_id sender_office_id
     *
     * @return $this
     */
    public function setSenderOfficeId($sender_office_id)
    {
        $this->container['sender_office_id'] = $sender_office_id;

        return $this;
    }

    /**
     * Gets recipient_first_name
     *
     * @return string
     */
    public function getRecipientFirstName()
    {
        return $this->container['recipient_first_name'];
    }

    /**
     * Sets recipient_first_name
     *
     * @param string $recipient_first_name recipient_first_name
     *
     * @return $this
     */
    public function setRecipientFirstName($recipient_first_name)
    {
        $this->container['recipient_first_name'] = $recipient_first_name;

        return $this;
    }

    /**
     * Gets recipient_last_name
     *
     * @return string
     */
    public function getRecipientLastName()
    {
        return $this->container['recipient_last_name'];
    }

    /**
     * Sets recipient_last_name
     *
     * @param string $recipient_last_name recipient_last_name
     *
     * @return $this
     */
    public function setRecipientLastName($recipient_last_name)
    {
        $this->container['recipient_last_name'] = $recipient_last_name;

        return $this;
    }

    /**
     * Gets recipient_patronymic
     *
     * @return string
     */
    public function getRecipientPatronymic()
    {
        return $this->container['recipient_patronymic'];
    }

    /**
     * Sets recipient_patronymic
     *
     * @param string $recipient_patronymic recipient_patronymic
     *
     * @return $this
     */
    public function setRecipientPatronymic($recipient_patronymic)
    {
        $this->container['recipient_patronymic'] = $recipient_patronymic;

        return $this;
    }

    /**
     * Gets recipient_phone
     *
     * @return string
     */
    public function getRecipientPhone()
    {
        return $this->container['recipient_phone'];
    }

    /**
     * Sets recipient_phone
     *
     * @param string $recipient_phone recipient_phone
     *
     * @return $this
     */
    public function setRecipientPhone($recipient_phone)
    {
        $this->container['recipient_phone'] = $recipient_phone;

        return $this;
    }

    /**
     * Gets recipient_email
     *
     * @return string
     */
    public function getRecipientEmail()
    {
        return $this->container['recipient_email'];
    }

    /**
     * Sets recipient_email
     *
     * @param string $recipient_email recipient_email
     *
     * @return $this
     */
    public function setRecipientEmail($recipient_email)
    {
        $this->container['recipient_email'] = $recipient_email;

        return $this;
    }

    /**
     * Gets recipient_city_id
     *
     * @return string
     */
    public function getRecipientCityId()
    {
        return $this->container['recipient_city_id'];
    }

    /**
     * Sets recipient_city_id
     *
     * @param string $recipient_city_id recipient_city_id
     *
     * @return $this
     */
    public function setRecipientCityId($recipient_city_id)
    {
        $this->container['recipient_city_id'] = $recipient_city_id;

        return $this;
    }

    /**
     * Gets recipient_office_id
     *
     * @return string
     */
    public function getRecipientOfficeId()
    {
        return $this->container['recipient_office_id'];
    }

    /**
     * Sets recipient_office_id
     *
     * @param string $recipient_office_id recipient_office_id
     *
     * @return $this
     */
    public function setRecipientOfficeId($recipient_office_id)
    {
        $this->container['recipient_office_id'] = $recipient_office_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


