<?php
/**
 * AdDetailsResponseDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Tests\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UAPAY EscrowBox
 *
 * Escrow box from UAPAY
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Server\Model;

/**
 * AdDetailsResponseDataTest Class Doc Comment
 *
 * @category    Class */
// * @description AdDetailsResponseData
/**
 * @package     Swagger\Server\Tests\Model
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AdDetailsResponseDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AdDetailsResponseData"
     */
    public function testAdDetailsResponseData()
    {
        $testAdDetailsResponseData = new AdDetailsResponseData();
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "externalId"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "productTitle"
     */
    public function testPropertyProductTitle()
    {
    }

    /**
     * Test attribute "productDescription"
     */
    public function testPropertyProductDescription()
    {
    }

    /**
     * Test attribute "productPrice"
     */
    public function testPropertyProductPrice()
    {
    }

    /**
     * Test attribute "productWeight"
     */
    public function testPropertyProductWeight()
    {
    }

    /**
     * Test attribute "sellerFirstName"
     */
    public function testPropertySellerFirstName()
    {
    }

    /**
     * Test attribute "sellerLastName"
     */
    public function testPropertySellerLastName()
    {
    }

    /**
     * Test attribute "sellerPatronymic"
     */
    public function testPropertySellerPatronymic()
    {
    }

    /**
     * Test attribute "sellerPhone"
     */
    public function testPropertySellerPhone()
    {
    }

    /**
     * Test attribute "sellerEmail"
     */
    public function testPropertySellerEmail()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "handlersConfigs"
     */
    public function testPropertyHandlersConfigs()
    {
    }

    /**
     * Test attribute "paymentsConfigs"
     */
    public function testPropertyPaymentsConfigs()
    {
    }
}
