<?php
/**
 * CreateDealRequestHandlerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Tests\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UAPAY EscrowBox
 *
 * Escrow box from UAPAY
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Server\Model;

/**
 * CreateDealRequestHandlerTest Class Doc Comment
 *
 * @category    Class */
// * @description CreateDealRequestHandler
/**
 * @package     Swagger\Server\Tests\Model
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateDealRequestHandlerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateDealRequestHandler"
     */
    public function testCreateDealRequestHandler()
    {
        $testCreateDealRequestHandler = new CreateDealRequestHandler();
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "senderFirstName"
     */
    public function testPropertySenderFirstName()
    {
    }

    /**
     * Test attribute "senderLastName"
     */
    public function testPropertySenderLastName()
    {
    }

    /**
     * Test attribute "senderPatronymic"
     */
    public function testPropertySenderPatronymic()
    {
    }

    /**
     * Test attribute "senderPhone"
     */
    public function testPropertySenderPhone()
    {
    }

    /**
     * Test attribute "senderEmail"
     */
    public function testPropertySenderEmail()
    {
    }

    /**
     * Test attribute "senderCityId"
     */
    public function testPropertySenderCityId()
    {
    }

    /**
     * Test attribute "senderOfficeId"
     */
    public function testPropertySenderOfficeId()
    {
    }

    /**
     * Test attribute "recipientFirstName"
     */
    public function testPropertyRecipientFirstName()
    {
    }

    /**
     * Test attribute "recipientLastName"
     */
    public function testPropertyRecipientLastName()
    {
    }

    /**
     * Test attribute "recipientPatronymic"
     */
    public function testPropertyRecipientPatronymic()
    {
    }

    /**
     * Test attribute "recipientPhone"
     */
    public function testPropertyRecipientPhone()
    {
    }

    /**
     * Test attribute "recipientEmail"
     */
    public function testPropertyRecipientEmail()
    {
    }

    /**
     * Test attribute "recipientCityId"
     */
    public function testPropertyRecipientCityId()
    {
    }

    /**
     * Test attribute "recipientOfficeId"
     */
    public function testPropertyRecipientOfficeId()
    {
    }
}
