<?php
/**
 * DealDetailsHandlerPaymentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Tests\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UAPAY EscrowBox
 *
 * Escrow box from UAPAY
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Server\Model;

/**
 * DealDetailsHandlerPaymentTest Class Doc Comment
 *
 * @category    Class */
// * @description DealDetailsHandlerPayment
/**
 * @package     Swagger\Server\Tests\Model
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DealDetailsHandlerPaymentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DealDetailsHandlerPayment"
     */
    public function testDealDetailsHandlerPayment()
    {
        $testDealDetailsHandlerPayment = new DealDetailsHandlerPayment();
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "commissionAmount"
     */
    public function testPropertyCommissionAmount()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "waitingFor"
     */
    public function testPropertyWaitingFor()
    {
    }

    /**
     * Test attribute "details"
     */
    public function testPropertyDetails()
    {
    }

    /**
     * Test attribute "payReceipt"
     */
    public function testPropertyPayReceipt()
    {
    }

    /**
     * Test attribute "reverseReceipt"
     */
    public function testPropertyReverseReceipt()
    {
    }

    /**
     * Test attribute "finishReceipt"
     */
    public function testPropertyFinishReceipt()
    {
    }
}
