<?php
/**
 * UpdateDealRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Tests\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UAPAY EscrowBox
 *
 * Escrow box from UAPAY
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Server\Model;

/**
 * UpdateDealRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description UpdateDealRequest
/**
 * @package     Swagger\Server\Tests\Model
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UpdateDealRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UpdateDealRequest"
     */
    public function testUpdateDealRequest()
    {
        $testUpdateDealRequest = new UpdateDealRequest();
    }

    /**
     * Test attribute "adId"
     */
    public function testPropertyAdId()
    {
    }

    /**
     * Test attribute "cartId"
     */
    public function testPropertyCartId()
    {
    }

    /**
     * Test attribute "productTitle"
     */
    public function testPropertyProductTitle()
    {
    }

    /**
     * Test attribute "productWeight"
     */
    public function testPropertyProductWeight()
    {
    }

    /**
     * Test attribute "productPrice"
     */
    public function testPropertyProductPrice()
    {
    }

    /**
     * Test attribute "sellerFirstName"
     */
    public function testPropertySellerFirstName()
    {
    }

    /**
     * Test attribute "sellerLastName"
     */
    public function testPropertySellerLastName()
    {
    }

    /**
     * Test attribute "sellerPatronymic"
     */
    public function testPropertySellerPatronymic()
    {
    }

    /**
     * Test attribute "sellerPhone"
     */
    public function testPropertySellerPhone()
    {
    }

    /**
     * Test attribute "sellerEmail"
     */
    public function testPropertySellerEmail()
    {
    }

    /**
     * Test attribute "buyerFirstName"
     */
    public function testPropertyBuyerFirstName()
    {
    }

    /**
     * Test attribute "buyerLastName"
     */
    public function testPropertyBuyerLastName()
    {
    }

    /**
     * Test attribute "buyerPatronymic"
     */
    public function testPropertyBuyerPatronymic()
    {
    }

    /**
     * Test attribute "buyerPhone"
     */
    public function testPropertyBuyerPhone()
    {
    }

    /**
     * Test attribute "buyerEmail"
     */
    public function testPropertyBuyerEmail()
    {
    }

    /**
     * Test attribute "payment"
     */
    public function testPropertyPayment()
    {
    }

    /**
     * Test attribute "handler"
     */
    public function testPropertyHandler()
    {
    }
}
