<?php
/**
 * CreateDealRequestHandlerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UAPAY EscrowBox
 *
 * Escrow box from UAPAY
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreateDealRequestHandlerTest Class Doc Comment
 *
 * @category    Class
 * @description CreateDealRequestHandler
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateDealRequestHandlerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateDealRequestHandler"
     */
    public function testCreateDealRequestHandler()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "sender_first_name"
     */
    public function testPropertySenderFirstName()
    {
    }

    /**
     * Test attribute "sender_last_name"
     */
    public function testPropertySenderLastName()
    {
    }

    /**
     * Test attribute "sender_patronymic"
     */
    public function testPropertySenderPatronymic()
    {
    }

    /**
     * Test attribute "sender_phone"
     */
    public function testPropertySenderPhone()
    {
    }

    /**
     * Test attribute "sender_email"
     */
    public function testPropertySenderEmail()
    {
    }

    /**
     * Test attribute "sender_city_id"
     */
    public function testPropertySenderCityId()
    {
    }

    /**
     * Test attribute "sender_office_id"
     */
    public function testPropertySenderOfficeId()
    {
    }

    /**
     * Test attribute "recipient_first_name"
     */
    public function testPropertyRecipientFirstName()
    {
    }

    /**
     * Test attribute "recipient_last_name"
     */
    public function testPropertyRecipientLastName()
    {
    }

    /**
     * Test attribute "recipient_patronymic"
     */
    public function testPropertyRecipientPatronymic()
    {
    }

    /**
     * Test attribute "recipient_phone"
     */
    public function testPropertyRecipientPhone()
    {
    }

    /**
     * Test attribute "recipient_email"
     */
    public function testPropertyRecipientEmail()
    {
    }

    /**
     * Test attribute "recipient_city_id"
     */
    public function testPropertyRecipientCityId()
    {
    }

    /**
     * Test attribute "recipient_office_id"
     */
    public function testPropertyRecipientOfficeId()
    {
    }
}
