<?php
/**
 * CreateDealRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UAPAY EscrowBox
 *
 * Escrow box from UAPAY
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreateDealRequestTest Class Doc Comment
 *
 * @category    Class
 * @description CreateDealRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateDealRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateDealRequest"
     */
    public function testCreateDealRequest()
    {
    }

    /**
     * Test attribute "ad_id"
     */
    public function testPropertyAdId()
    {
    }

    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "cart_id"
     */
    public function testPropertyCartId()
    {
    }

    /**
     * Test attribute "product_title"
     */
    public function testPropertyProductTitle()
    {
    }

    /**
     * Test attribute "product_weight"
     */
    public function testPropertyProductWeight()
    {
    }

    /**
     * Test attribute "product_price"
     */
    public function testPropertyProductPrice()
    {
    }

    /**
     * Test attribute "seller_first_name"
     */
    public function testPropertySellerFirstName()
    {
    }

    /**
     * Test attribute "seller_last_name"
     */
    public function testPropertySellerLastName()
    {
    }

    /**
     * Test attribute "seller_patronymic"
     */
    public function testPropertySellerPatronymic()
    {
    }

    /**
     * Test attribute "seller_phone"
     */
    public function testPropertySellerPhone()
    {
    }

    /**
     * Test attribute "seller_email"
     */
    public function testPropertySellerEmail()
    {
    }

    /**
     * Test attribute "buyer_first_name"
     */
    public function testPropertyBuyerFirstName()
    {
    }

    /**
     * Test attribute "buyer_last_name"
     */
    public function testPropertyBuyerLastName()
    {
    }

    /**
     * Test attribute "buyer_patronymic"
     */
    public function testPropertyBuyerPatronymic()
    {
    }

    /**
     * Test attribute "buyer_phone"
     */
    public function testPropertyBuyerPhone()
    {
    }

    /**
     * Test attribute "buyer_email"
     */
    public function testPropertyBuyerEmail()
    {
    }

    /**
     * Test attribute "lg"
     */
    public function testPropertyLg()
    {
    }

    /**
     * Test attribute "payment"
     */
    public function testPropertyPayment()
    {
    }

    /**
     * Test attribute "handler"
     */
    public function testPropertyHandler()
    {
    }
}
