<?php
/**
 * CartsApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UAPAY EscrowBox
 *
 * Escrow box from UAPAY
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use Swagger\Server\Model\CartDetailsResponse;
use Swagger\Server\Model\CartIdsResponse;
use Swagger\Server\Model\CreateCartRequest;

/**
 * CartsApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  Swagger\Server\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
interface CartsApiInterface
{

    /**
     * Sets authentication method basicAuth
     *
     * @param string $value Value of the basicAuth authentication method.
     *
     * @return void
     */
    public function setbasicAuth($value);

    /**
     * Operation cartsIdGet
     *
     * Show cart and its deals
     *
     * @param  int $id   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return Swagger\Server\Model\CartDetailsResponse[]
     *
     */
    public function cartsIdGet($id, &$responseCode, array &$responseHeaders);

    /**
     * Operation cartsPost
     *
     * Create a cart
     *
     * @param  Swagger\Server\Model\CreateCartRequest $body   (optional)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return Swagger\Server\Model\CartIdsResponse[]
     *
     */
    public function cartsPost(CreateCartRequest $body = null, &$responseCode, array &$responseHeaders);
}
