<?php
/**
 * HelpersApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UAPAY EscrowBox
 *
 * Escrow box from UAPAY
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use Swagger\Server\Model\HandlerCitiesResponse;
use Swagger\Server\Model\HandlerCostResponse;
use Swagger\Server\Model\HandlerOfficesResponse;
use Swagger\Server\Model\PayerCommissionAmountResponse;
use Swagger\Server\Model\PayerCommissionResponse;

/**
 * HelpersApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  Swagger\Server\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
interface HelpersApiInterface
{

    /**
     * Sets authentication method basicAuth
     *
     * @param string $value Value of the basicAuth authentication method.
     *
     * @return void
     */
    public function setbasicAuth($value);

    /**
     * Operation handlersHandlerTypeCitiesCityIdOfficesGet
     *
     * List offices from handler by cityId
     *
     * @param  string $handlerType   (required)
     * @param  string $cityId   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return Swagger\Server\Model\HandlerOfficesResponse[]
     *
     */
    public function handlersHandlerTypeCitiesCityIdOfficesGet($handlerType, $cityId, &$responseCode, array &$responseHeaders);

    /**
     * Operation handlersHandlerTypeCitiesGet
     *
     * List cities from handler
     *
     * @param  string $handlerType   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return Swagger\Server\Model\HandlerCitiesResponse[]
     *
     */
    public function handlersHandlerTypeCitiesGet($handlerType, &$responseCode, array &$responseHeaders);

    /**
     * Operation handlersHandlerTypeCostsGet
     *
     * Calculate delivery cost
     *
     * @param  string $handlerType   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return Swagger\Server\Model\HandlerCostResponse[]
     *
     */
    public function handlersHandlerTypeCostsGet($handlerType, &$responseCode, array &$responseHeaders);

    /**
     * Operation payersPayerTypeCommissionAmountGet
     *
     * Calculate commission amount from income amount for payer
     *
     * @param  string $payerType   (required)
     * @param  int $amount   (optional)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return Swagger\Server\Model\PayerCommissionAmountResponse[]
     *
     */
    public function payersPayerTypeCommissionAmountGet($payerType, $amount = null, &$responseCode, array &$responseHeaders);

    /**
     * Operation payersPayerTypeGet
     *
     * Get commission object of payer
     *
     * @param  string $payerType   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return Swagger\Server\Model\PayerCommissionResponse[]
     *
     */
    public function payersPayerTypeGet($payerType, &$responseCode, array &$responseHeaders);
}
